### ISSUE TITLE
.map() issue

### ISSUE THREAD

**Issue by marknosal** [learn-co-curriculum/phase-1-algorithms-palindrome#3]
### Canvas Link

https://learning.flatironschool.com/courses/6190/assignments/225637?module_item_id=526926

### Concern

If you check out my code.  When lines 5-10 are commented out.  The palindromes always return false.  Even though when you console.log them in the DOM you can see they equal each other.  Then when I comment lines 5-10 back in to change the array back into a string I pass the tests.  Its very strange because the code logic makes sense.  A palindrome is a palindrome whether its in an array format or a string format.  I'm thinking it might be because I used to the .map function?  If you check this out could you send me a slack?  I'm just kinda curious about it.

function isPalindrome(string) {
  const arrayForward = string.split('')
  const arrayBackward = []
  arrayForward.map(letter => arrayBackward.unshift(letter))
  // console.log(arrayForward)
  // console.log(arrayBackward)
  // const arrayForward2 = arrayForward.join('')
  // const arrayBackward2 = arrayBackward.join('')
  // console.log(arrayForward2)
  // console.log(arrayBackward2)
  if (arrayForward === arrayBackward) {
    return true
    console.log('true')
  } else {
    return false
    console.log('false')
  }
}

module.exports = isPalindrome;

### Additional Context

I failed all the tests that should return true.  Until I changed the array back into a string

### Suggested Changes

Maybe its the .map() I used?

**Comment by lizbur10** [comment]
Hi @marknosal! I agree that it seems like it should work using either arrays or strings, but in JavaScript, checking for equality works differently for objects and arrays than it does for literal values (like strings). You will learn more about this a bit later in the curriculum.

I'm going to go ahead and close this issue. Nice job getting it to work using strings! 💙
